<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="78" />
      <entry action="$Delete" count="145" />
      <entry action="$Paste" count="92" />
      <entry action="$SelectAll" count="116" />
      <entry action="$Undo" count="5855" />
      <entry action="About" count="6" />
      <entry action="Android Profiler" count="1" />
      <entry action="Android.AnalyzeApk" count="2" />
      <entry action="Android.BuildApk" count="24" />
      <entry action="Android.CreateSampleDataDirectory" count="1" />
      <entry action="Android.GenerateSignedApk" count="2" />
      <entry action="Android.RunAndroidAvdManager" count="54" />
      <entry action="Android.RunAndroidSdkManager" count="20" />
      <entry action="Android.SyncProject" count="295" />
      <entry action="AndroidConnectDebuggerAction" count="6" />
      <entry action="AndroidMigrateToAndroidxAction" count="1" />
      <entry action="AndroidMigrateToAppCompatAction" count="1" />
      <entry action="AttachDebuggerAction" count="1" />
      <entry action="CheckForUpdate" count="1" />
      <entry action="CheckinProject" count="1" />
      <entry action="ChooseDebugConfiguration" count="2" />
      <entry action="ChooseRunConfiguration" count="6" />
      <entry action="ClassNameCompletion" count="2" />
      <entry action="CleanGradleProject" count="31" />
      <entry action="CloseAllEditors" count="1" />
      <entry action="CloseContent" count="7" />
      <entry action="CloseProject" count="1" />
      <entry action="Cluestick.SearchMenu" count="3" />
      <entry action="CodeCompletion" count="4541" />
      <entry action="CommentByLineComment" count="3" />
      <entry action="CompareClipboardWithSelection" count="1" />
      <entry action="CopyElement" count="14" />
      <entry action="CreateResourceBundle" count="1" />
      <entry action="CreateRunConfiguration" count="1" />
      <entry action="Debug" count="3" />
      <entry action="DialogOkAction Enter" count="20" />
      <entry action="EditSource" count="2" />
      <entry action="EditorBackSpace" count="13631" />
      <entry action="EditorChooseLookupItem" count="3447" />
      <entry action="EditorCopy" count="2243" />
      <entry action="EditorCut" count="389" />
      <entry action="EditorDelete" count="241" />
      <entry action="EditorDeleteLine" count="169" />
      <entry action="EditorDeleteToWordStart" count="1" />
      <entry action="EditorDown" count="7566" />
      <entry action="EditorDownWithSelection" count="7" />
      <entry action="EditorDuplicate" count="12" />
      <entry action="EditorEnter" count="3718" />
      <entry action="EditorIndentSelection" count="58" />
      <entry action="EditorLeft" count="3133" />
      <entry action="EditorLeftWithSelection" count="1337" />
      <entry action="EditorNextWord" count="9" />
      <entry action="EditorPaste" count="3620" />
      <entry action="EditorPreviousWord" count="1" />
      <entry action="EditorRight" count="2430" />
      <entry action="EditorRightWithSelection" count="3542" />
      <entry action="EditorSplitLine" count="5" />
      <entry action="EditorStartNewLine" count="5" />
      <entry action="EditorTab" count="1279" />
      <entry action="EditorToggleInsertState" count="5" />
      <entry action="EditorUnindentSelection" count="81" />
      <entry action="EditorUp" count="2346" />
      <entry action="EditorUpWithSelection" count="7" />
      <entry action="ExportSettings" count="1" />
      <entry action="FileChooser.GotoHome" count="4" />
      <entry action="FileChooser.NewFolder" count="16" />
      <entry action="Find" count="87" />
      <entry action="FindNext" count="3" />
      <entry action="Generate" count="14" />
      <entry action="GotoDeclaration" count="52" />
      <entry action="HideAllWindows" count="5" />
      <entry action="ImplementMethods" count="1" />
      <entry action="ImportProject" count="1" />
      <entry action="InvalidateCaches" count="12" />
      <entry action="ManageRecentProjects" count="1" />
      <entry action="MaximizeToolWindow" count="1" />
      <entry action="NewAndroidImageAsset" count="7" />
      <entry action="NewAndroidVectorAsset" count="43" />
      <entry action="NewClass" count="16" />
      <entry action="NewDir" count="18" />
      <entry action="NewProject" count="64" />
      <entry action="NewScratchFile" count="4" />
      <entry action="NextTemplateVariable" count="1" />
      <entry action="OpenFile" count="149" />
      <entry action="ParameterInfo" count="1" />
      <entry action="PasteMultiple" count="1" />
      <entry action="RebuildGradleProject" count="30" />
      <entry action="RenameElement" count="39" />
      <entry action="Run" count="2010" />
      <entry action="SafeDelete" count="1" />
      <entry action="SaveAll" count="14648" />
      <entry action="SearchEverywhere" count="3" />
      <entry action="SendEOF" count="1" />
      <entry action="ShowErrorDescription" count="1" />
      <entry action="ShowFilePath" count="3" />
      <entry action="ShowIntentionActions" count="42" />
      <entry action="ShowPopupMenu" count="1" />
      <entry action="ShowSettings" count="2" />
      <entry action="SmartTypeCompletion" count="6" />
      <entry action="S